# Generated by Django 2.2.3 on 2019-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
