# Generated by Django 2.2.3 on 2019-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0002_auto_20190703_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='color',
        ),
        migrations.AddField(
            model_name='graph',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='graphselector',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='graphselector',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
