# Generated by Django 2.2.3 on 2019-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0003_auto_20190704_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='unit',
            field=models.CharField(blank='', default='', max_length=4),
        ),
    ]
