# Generated by Django 2.2.3 on 2019-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0004_type_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='unit',
            field=models.CharField(blank='', default='', max_length=8),
        ),
    ]
