# Generated by Django 2.2.3 on 2019-07-04 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0008_graph_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
