# Generated by Django 2.2.3 on 2019-07-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0010_graphselector_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('dashboard', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DjangoGraphs.GraphSelector')),
            ],
        ),
    ]
