# Generated by Django 2.2.3 on 2019-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0012_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='order',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='graphselector',
            name='order',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
