# Generated by Django 2.2.3 on 2019-07-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGraphs', '0013_auto_20190708_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graph',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphselector',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
